[package]
name = "color-theme-luaunator"
version = "0.1.0"
edition = "2024"

[dependencies]
json5 = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1.0"
